language: node_js
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
branches:
  only:
  - "/^v[0-9]/"
after_success:
- npm run coverage
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
before_deploy:
- npm run-script build
- npm run-script bundle
- mkdir -p deploy/inquisitor/$TRAVIS_TAG
- cp deploy/inquisitor/latest/inquisitor.bundle.js deploy/inquisitor/$TRAVIS_TAG/inquisitor.bundle.js
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: PwYDKmVd0LktxmWlc6tVBBeYezuseY2ojG7I9KMs78j2HmMdvFb9cwCdjiz3ShYjht67z/1X5XElv4C5lb59jUmVBC/4Zo38pig23up/pr5K3FRXCUFoVcuyx2c+ajWgCo3wl5+5M1jmNUuyW1gqzdUrX1gGica6ls/pBq4QAWZuzkuC12P6kS6/800lYNqXLK7VFuw8sOm1pQCh6emXVSbR2lWwnKV9oh8Uyvbaen2fvC0ChVLxES/q925YVZgmXnlwlGyd+856eDV0b9xhJCETPrLNd88v7l4p+9WACZADjvQhKam2XqYH62x5gw8tXdPYDIkxB3EM6fxpSEpV8fIMOMqmu/gsdzMTwjjgIDI3ue6a0i4MSsjd7rS8b6QbMxYd4sClvoFs+ZwavDHeInexPhCeSk4giqxPZF3FX794+sXcXSkqjxf95G2fRsjtPVTg1KSBrKsH+CjJHhVeJwWl9kEOJBI2BjTRFJGyD6ox9fVKWbr7uGcJMaDIDdc05YfDGl4ANpSl1v76R/SLAnRwM07N5Hw2jopJfBqKQqvr3LrSOM2Mgl4Q/bgTOkFj/AeXoyYiiIX4t3F6n4MvaMN5LVS64p2SstOVa7nhrFsg7BoLNszs0KslRfFEZ34zP4FCTrLlIE0aA5Ej8kfpq8ISuGu8ydUR1VQXbHZGfQE=
  on:
    tags: true
    repo: octoblu/meshblu-inquisitor
